spring:
  application:
    name: case-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          # 是否与服务发现组件进行结合，通过serviceId转发到具体的服务实例。默认为false，为true代表开启基于服务发现的路由规则。
          enabled: true
          # 配置之后访问时无需大写
          lower-case-service-id: true
      # 设置路由：所有的请求都会路由到http://127.0.0.1:8081/**
      routes:
      - id: cloud-client-app
        uri: http://127.0.0.1:8081
        order: 0
        predicates:
        - Path=/**
      - id: cloud-client-pc
        uri: http://www.baidu.com
        order: 0
        predicates:
        - Path=/pc/**
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        # 健康检测20s once
        health-check-interval: 10s
        health-check-path: /gateway_health

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled: false

server:
  #网关服务监听 9000 端口
  port: 9000

logging:
  level:
    #调整相关包的 log 级别，以便排查问题
    org.springframework.cloud.gateway: debug