# Redis基础配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 1000ms
        min-idle: 5